title: Arachne
description: "A Gaming Podcast â€” episodes, events, videos, and community updates."
url: "https://inventorofsoup.github.io"
baseurl: "/ArachneAWebsite"

# IMPORTANT: remove theme so we use our own layouts
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
permalink: /posts/:title/
